package com.medicalcare.user.pojo;

import java.util.ArrayList;
import java.util.List;

public class DrugExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public DrugExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDrugidIsNull() {
            addCriterion("drugId is null");
            return (Criteria) this;
        }

        public Criteria andDrugidIsNotNull() {
            addCriterion("drugId is not null");
            return (Criteria) this;
        }

        public Criteria andDrugidEqualTo(Integer value) {
            addCriterion("drugId =", value, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidNotEqualTo(Integer value) {
            addCriterion("drugId <>", value, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidGreaterThan(Integer value) {
            addCriterion("drugId >", value, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidGreaterThanOrEqualTo(Integer value) {
            addCriterion("drugId >=", value, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidLessThan(Integer value) {
            addCriterion("drugId <", value, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidLessThanOrEqualTo(Integer value) {
            addCriterion("drugId <=", value, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidIn(List<Integer> values) {
            addCriterion("drugId in", values, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidNotIn(List<Integer> values) {
            addCriterion("drugId not in", values, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidBetween(Integer value1, Integer value2) {
            addCriterion("drugId between", value1, value2, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrugidNotBetween(Integer value1, Integer value2) {
            addCriterion("drugId not between", value1, value2, "drugid");
            return (Criteria) this;
        }

        public Criteria andDrughospnameIsNull() {
            addCriterion("drugHospName is null");
            return (Criteria) this;
        }

        public Criteria andDrughospnameIsNotNull() {
            addCriterion("drugHospName is not null");
            return (Criteria) this;
        }

        public Criteria andDrughospnameEqualTo(String value) {
            addCriterion("drugHospName =", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameNotEqualTo(String value) {
            addCriterion("drugHospName <>", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameGreaterThan(String value) {
            addCriterion("drugHospName >", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameGreaterThanOrEqualTo(String value) {
            addCriterion("drugHospName >=", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameLessThan(String value) {
            addCriterion("drugHospName <", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameLessThanOrEqualTo(String value) {
            addCriterion("drugHospName <=", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameLike(String value) {
            addCriterion("drugHospName like", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameNotLike(String value) {
            addCriterion("drugHospName not like", value, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameIn(List<String> values) {
            addCriterion("drugHospName in", values, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameNotIn(List<String> values) {
            addCriterion("drugHospName not in", values, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameBetween(String value1, String value2) {
            addCriterion("drugHospName between", value1, value2, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrughospnameNotBetween(String value1, String value2) {
            addCriterion("drugHospName not between", value1, value2, "drughospname");
            return (Criteria) this;
        }

        public Criteria andDrugnameIsNull() {
            addCriterion("drugName is null");
            return (Criteria) this;
        }

        public Criteria andDrugnameIsNotNull() {
            addCriterion("drugName is not null");
            return (Criteria) this;
        }

        public Criteria andDrugnameEqualTo(String value) {
            addCriterion("drugName =", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameNotEqualTo(String value) {
            addCriterion("drugName <>", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameGreaterThan(String value) {
            addCriterion("drugName >", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameGreaterThanOrEqualTo(String value) {
            addCriterion("drugName >=", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameLessThan(String value) {
            addCriterion("drugName <", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameLessThanOrEqualTo(String value) {
            addCriterion("drugName <=", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameLike(String value) {
            addCriterion("drugName like", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameNotLike(String value) {
            addCriterion("drugName not like", value, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameIn(List<String> values) {
            addCriterion("drugName in", values, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameNotIn(List<String> values) {
            addCriterion("drugName not in", values, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameBetween(String value1, String value2) {
            addCriterion("drugName between", value1, value2, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugnameNotBetween(String value1, String value2) {
            addCriterion("drugName not between", value1, value2, "drugname");
            return (Criteria) this;
        }

        public Criteria andDrugdoseIsNull() {
            addCriterion("drugDose is null");
            return (Criteria) this;
        }

        public Criteria andDrugdoseIsNotNull() {
            addCriterion("drugDose is not null");
            return (Criteria) this;
        }

        public Criteria andDrugdoseEqualTo(String value) {
            addCriterion("drugDose =", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseNotEqualTo(String value) {
            addCriterion("drugDose <>", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseGreaterThan(String value) {
            addCriterion("drugDose >", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseGreaterThanOrEqualTo(String value) {
            addCriterion("drugDose >=", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseLessThan(String value) {
            addCriterion("drugDose <", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseLessThanOrEqualTo(String value) {
            addCriterion("drugDose <=", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseLike(String value) {
            addCriterion("drugDose like", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseNotLike(String value) {
            addCriterion("drugDose not like", value, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseIn(List<String> values) {
            addCriterion("drugDose in", values, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseNotIn(List<String> values) {
            addCriterion("drugDose not in", values, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseBetween(String value1, String value2) {
            addCriterion("drugDose between", value1, value2, "drugdose");
            return (Criteria) this;
        }

        public Criteria andDrugdoseNotBetween(String value1, String value2) {
            addCriterion("drugDose not between", value1, value2, "drugdose");
            return (Criteria) this;
        }

        public Criteria andSingledoseIsNull() {
            addCriterion("singleDose is null");
            return (Criteria) this;
        }

        public Criteria andSingledoseIsNotNull() {
            addCriterion("singleDose is not null");
            return (Criteria) this;
        }

        public Criteria andSingledoseEqualTo(String value) {
            addCriterion("singleDose =", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseNotEqualTo(String value) {
            addCriterion("singleDose <>", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseGreaterThan(String value) {
            addCriterion("singleDose >", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseGreaterThanOrEqualTo(String value) {
            addCriterion("singleDose >=", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseLessThan(String value) {
            addCriterion("singleDose <", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseLessThanOrEqualTo(String value) {
            addCriterion("singleDose <=", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseLike(String value) {
            addCriterion("singleDose like", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseNotLike(String value) {
            addCriterion("singleDose not like", value, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseIn(List<String> values) {
            addCriterion("singleDose in", values, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseNotIn(List<String> values) {
            addCriterion("singleDose not in", values, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseBetween(String value1, String value2) {
            addCriterion("singleDose between", value1, value2, "singledose");
            return (Criteria) this;
        }

        public Criteria andSingledoseNotBetween(String value1, String value2) {
            addCriterion("singleDose not between", value1, value2, "singledose");
            return (Criteria) this;
        }

        public Criteria andDoseunitIsNull() {
            addCriterion("doseUnit is null");
            return (Criteria) this;
        }

        public Criteria andDoseunitIsNotNull() {
            addCriterion("doseUnit is not null");
            return (Criteria) this;
        }

        public Criteria andDoseunitEqualTo(String value) {
            addCriterion("doseUnit =", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitNotEqualTo(String value) {
            addCriterion("doseUnit <>", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitGreaterThan(String value) {
            addCriterion("doseUnit >", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitGreaterThanOrEqualTo(String value) {
            addCriterion("doseUnit >=", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitLessThan(String value) {
            addCriterion("doseUnit <", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitLessThanOrEqualTo(String value) {
            addCriterion("doseUnit <=", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitLike(String value) {
            addCriterion("doseUnit like", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitNotLike(String value) {
            addCriterion("doseUnit not like", value, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitIn(List<String> values) {
            addCriterion("doseUnit in", values, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitNotIn(List<String> values) {
            addCriterion("doseUnit not in", values, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitBetween(String value1, String value2) {
            addCriterion("doseUnit between", value1, value2, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDoseunitNotBetween(String value1, String value2) {
            addCriterion("doseUnit not between", value1, value2, "doseunit");
            return (Criteria) this;
        }

        public Criteria andDrugstateIsNull() {
            addCriterion("drugState is null");
            return (Criteria) this;
        }

        public Criteria andDrugstateIsNotNull() {
            addCriterion("drugState is not null");
            return (Criteria) this;
        }

        public Criteria andDrugstateEqualTo(String value) {
            addCriterion("drugState =", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateNotEqualTo(String value) {
            addCriterion("drugState <>", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateGreaterThan(String value) {
            addCriterion("drugState >", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateGreaterThanOrEqualTo(String value) {
            addCriterion("drugState >=", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateLessThan(String value) {
            addCriterion("drugState <", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateLessThanOrEqualTo(String value) {
            addCriterion("drugState <=", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateLike(String value) {
            addCriterion("drugState like", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateNotLike(String value) {
            addCriterion("drugState not like", value, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateIn(List<String> values) {
            addCriterion("drugState in", values, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateNotIn(List<String> values) {
            addCriterion("drugState not in", values, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateBetween(String value1, String value2) {
            addCriterion("drugState between", value1, value2, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugstateNotBetween(String value1, String value2) {
            addCriterion("drugState not between", value1, value2, "drugstate");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryIsNull() {
            addCriterion("drugCategory is null");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryIsNotNull() {
            addCriterion("drugCategory is not null");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryEqualTo(String value) {
            addCriterion("drugCategory =", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryNotEqualTo(String value) {
            addCriterion("drugCategory <>", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryGreaterThan(String value) {
            addCriterion("drugCategory >", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryGreaterThanOrEqualTo(String value) {
            addCriterion("drugCategory >=", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryLessThan(String value) {
            addCriterion("drugCategory <", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryLessThanOrEqualTo(String value) {
            addCriterion("drugCategory <=", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryLike(String value) {
            addCriterion("drugCategory like", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryNotLike(String value) {
            addCriterion("drugCategory not like", value, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryIn(List<String> values) {
            addCriterion("drugCategory in", values, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryNotIn(List<String> values) {
            addCriterion("drugCategory not in", values, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryBetween(String value1, String value2) {
            addCriterion("drugCategory between", value1, value2, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcategoryNotBetween(String value1, String value2) {
            addCriterion("drugCategory not between", value1, value2, "drugcategory");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemIsNull() {
            addCriterion("drugCureItem is null");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemIsNotNull() {
            addCriterion("drugCureItem is not null");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemEqualTo(String value) {
            addCriterion("drugCureItem =", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemNotEqualTo(String value) {
            addCriterion("drugCureItem <>", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemGreaterThan(String value) {
            addCriterion("drugCureItem >", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemGreaterThanOrEqualTo(String value) {
            addCriterion("drugCureItem >=", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemLessThan(String value) {
            addCriterion("drugCureItem <", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemLessThanOrEqualTo(String value) {
            addCriterion("drugCureItem <=", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemLike(String value) {
            addCriterion("drugCureItem like", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemNotLike(String value) {
            addCriterion("drugCureItem not like", value, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemIn(List<String> values) {
            addCriterion("drugCureItem in", values, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemNotIn(List<String> values) {
            addCriterion("drugCureItem not in", values, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemBetween(String value1, String value2) {
            addCriterion("drugCureItem between", value1, value2, "drugcureitem");
            return (Criteria) this;
        }

        public Criteria andDrugcureitemNotBetween(String value1, String value2) {
            addCriterion("drugCureItem not between", value1, value2, "drugcureitem");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 14 20:40:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}