package com.medicalcare.user.pojo;

import java.util.Date;

public class Elderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer elderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String eldername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderAddress
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String elderaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderSex
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer eldersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderBirth
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Date elderbirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderAge
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer elderage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderNation
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String eldernation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderIdNumber
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer elderidnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderEmail
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String elderemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderPhoto
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String elderphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderCompany
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String eldercompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderinfo.elderPhysicalState
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String elderphysicalstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderId
     *
     * @return the value of elderinfo.elderId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getElderid() {
        return elderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderId
     *
     * @param elderid the value for elderinfo.elderId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderid(Integer elderid) {
        this.elderid = elderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderName
     *
     * @return the value of elderinfo.elderName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getEldername() {
        return eldername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderName
     *
     * @param eldername the value for elderinfo.elderName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setEldername(String eldername) {
        this.eldername = eldername == null ? null : eldername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderAddress
     *
     * @return the value of elderinfo.elderAddress
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getElderaddress() {
        return elderaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderAddress
     *
     * @param elderaddress the value for elderinfo.elderAddress
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderaddress(String elderaddress) {
        this.elderaddress = elderaddress == null ? null : elderaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderSex
     *
     * @return the value of elderinfo.elderSex
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getEldersex() {
        return eldersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderSex
     *
     * @param eldersex the value for elderinfo.elderSex
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setEldersex(Integer eldersex) {
        this.eldersex = eldersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderBirth
     *
     * @return the value of elderinfo.elderBirth
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Date getElderbirth() {
        return elderbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderBirth
     *
     * @param elderbirth the value for elderinfo.elderBirth
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderbirth(Date elderbirth) {
        this.elderbirth = elderbirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderAge
     *
     * @return the value of elderinfo.elderAge
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getElderage() {
        return elderage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderAge
     *
     * @param elderage the value for elderinfo.elderAge
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderage(Integer elderage) {
        this.elderage = elderage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderNation
     *
     * @return the value of elderinfo.elderNation
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getEldernation() {
        return eldernation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderNation
     *
     * @param eldernation the value for elderinfo.elderNation
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setEldernation(String eldernation) {
        this.eldernation = eldernation == null ? null : eldernation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderIdNumber
     *
     * @return the value of elderinfo.elderIdNumber
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getElderidnumber() {
        return elderidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderIdNumber
     *
     * @param elderidnumber the value for elderinfo.elderIdNumber
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderidnumber(Integer elderidnumber) {
        this.elderidnumber = elderidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderEmail
     *
     * @return the value of elderinfo.elderEmail
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getElderemail() {
        return elderemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderEmail
     *
     * @param elderemail the value for elderinfo.elderEmail
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderemail(String elderemail) {
        this.elderemail = elderemail == null ? null : elderemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderPhoto
     *
     * @return the value of elderinfo.elderPhoto
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getElderphoto() {
        return elderphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderPhoto
     *
     * @param elderphoto the value for elderinfo.elderPhoto
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderphoto(String elderphoto) {
        this.elderphoto = elderphoto == null ? null : elderphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderCompany
     *
     * @return the value of elderinfo.elderCompany
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getEldercompany() {
        return eldercompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderCompany
     *
     * @param eldercompany the value for elderinfo.elderCompany
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setEldercompany(String eldercompany) {
        this.eldercompany = eldercompany == null ? null : eldercompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderinfo.elderPhysicalState
     *
     * @return the value of elderinfo.elderPhysicalState
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getElderphysicalstate() {
        return elderphysicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderinfo.elderPhysicalState
     *
     * @param elderphysicalstate the value for elderinfo.elderPhysicalState
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setElderphysicalstate(String elderphysicalstate) {
        this.elderphysicalstate = elderphysicalstate == null ? null : elderphysicalstate.trim();
    }
}