package com.medicalcare.user.pojo;

public class Elderhealthinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.healthId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer healthid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.userId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.bloodSuger
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String bloodsuger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.bloodPressure
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String bloodpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.bloodOxygen
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String bloodoxygen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.heightWeight
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String heightweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.cholesterol
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String cholesterol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.uricAcid
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String uricacid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.boneDensity
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String bonedensity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.sleep
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String sleep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderhealthinfo.heartRate
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String heartrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.healthId
     *
     * @return the value of elderhealthinfo.healthId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getHealthid() {
        return healthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.healthId
     *
     * @param healthid the value for elderhealthinfo.healthId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHealthid(Integer healthid) {
        this.healthid = healthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.userId
     *
     * @return the value of elderhealthinfo.userId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.userId
     *
     * @param userid the value for elderhealthinfo.userId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.bloodSuger
     *
     * @return the value of elderhealthinfo.bloodSuger
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getBloodsuger() {
        return bloodsuger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.bloodSuger
     *
     * @param bloodsuger the value for elderhealthinfo.bloodSuger
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setBloodsuger(String bloodsuger) {
        this.bloodsuger = bloodsuger == null ? null : bloodsuger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.bloodPressure
     *
     * @return the value of elderhealthinfo.bloodPressure
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getBloodpressure() {
        return bloodpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.bloodPressure
     *
     * @param bloodpressure the value for elderhealthinfo.bloodPressure
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setBloodpressure(String bloodpressure) {
        this.bloodpressure = bloodpressure == null ? null : bloodpressure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.bloodOxygen
     *
     * @return the value of elderhealthinfo.bloodOxygen
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getBloodoxygen() {
        return bloodoxygen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.bloodOxygen
     *
     * @param bloodoxygen the value for elderhealthinfo.bloodOxygen
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setBloodoxygen(String bloodoxygen) {
        this.bloodoxygen = bloodoxygen == null ? null : bloodoxygen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.heightWeight
     *
     * @return the value of elderhealthinfo.heightWeight
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getHeightweight() {
        return heightweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.heightWeight
     *
     * @param heightweight the value for elderhealthinfo.heightWeight
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHeightweight(String heightweight) {
        this.heightweight = heightweight == null ? null : heightweight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.cholesterol
     *
     * @return the value of elderhealthinfo.cholesterol
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getCholesterol() {
        return cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.cholesterol
     *
     * @param cholesterol the value for elderhealthinfo.cholesterol
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setCholesterol(String cholesterol) {
        this.cholesterol = cholesterol == null ? null : cholesterol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.uricAcid
     *
     * @return the value of elderhealthinfo.uricAcid
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getUricacid() {
        return uricacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.uricAcid
     *
     * @param uricacid the value for elderhealthinfo.uricAcid
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUricacid(String uricacid) {
        this.uricacid = uricacid == null ? null : uricacid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.boneDensity
     *
     * @return the value of elderhealthinfo.boneDensity
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getBonedensity() {
        return bonedensity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.boneDensity
     *
     * @param bonedensity the value for elderhealthinfo.boneDensity
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setBonedensity(String bonedensity) {
        this.bonedensity = bonedensity == null ? null : bonedensity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.sleep
     *
     * @return the value of elderhealthinfo.sleep
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getSleep() {
        return sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.sleep
     *
     * @param sleep the value for elderhealthinfo.sleep
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setSleep(String sleep) {
        this.sleep = sleep == null ? null : sleep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderhealthinfo.heartRate
     *
     * @return the value of elderhealthinfo.heartRate
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getHeartrate() {
        return heartrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderhealthinfo.heartRate
     *
     * @param heartrate the value for elderhealthinfo.heartRate
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHeartrate(String heartrate) {
        this.heartrate = heartrate == null ? null : heartrate.trim();
    }
}