package com.medicalcare.user.pojo;

import java.util.ArrayList;
import java.util.List;

public class ElderhealthinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public ElderhealthinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHealthidIsNull() {
            addCriterion("healthId is null");
            return (Criteria) this;
        }

        public Criteria andHealthidIsNotNull() {
            addCriterion("healthId is not null");
            return (Criteria) this;
        }

        public Criteria andHealthidEqualTo(Integer value) {
            addCriterion("healthId =", value, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidNotEqualTo(Integer value) {
            addCriterion("healthId <>", value, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidGreaterThan(Integer value) {
            addCriterion("healthId >", value, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidGreaterThanOrEqualTo(Integer value) {
            addCriterion("healthId >=", value, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidLessThan(Integer value) {
            addCriterion("healthId <", value, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidLessThanOrEqualTo(Integer value) {
            addCriterion("healthId <=", value, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidIn(List<Integer> values) {
            addCriterion("healthId in", values, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidNotIn(List<Integer> values) {
            addCriterion("healthId not in", values, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidBetween(Integer value1, Integer value2) {
            addCriterion("healthId between", value1, value2, "healthid");
            return (Criteria) this;
        }

        public Criteria andHealthidNotBetween(Integer value1, Integer value2) {
            addCriterion("healthId not between", value1, value2, "healthid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andBloodsugerIsNull() {
            addCriterion("bloodSuger is null");
            return (Criteria) this;
        }

        public Criteria andBloodsugerIsNotNull() {
            addCriterion("bloodSuger is not null");
            return (Criteria) this;
        }

        public Criteria andBloodsugerEqualTo(String value) {
            addCriterion("bloodSuger =", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerNotEqualTo(String value) {
            addCriterion("bloodSuger <>", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerGreaterThan(String value) {
            addCriterion("bloodSuger >", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerGreaterThanOrEqualTo(String value) {
            addCriterion("bloodSuger >=", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerLessThan(String value) {
            addCriterion("bloodSuger <", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerLessThanOrEqualTo(String value) {
            addCriterion("bloodSuger <=", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerLike(String value) {
            addCriterion("bloodSuger like", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerNotLike(String value) {
            addCriterion("bloodSuger not like", value, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerIn(List<String> values) {
            addCriterion("bloodSuger in", values, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerNotIn(List<String> values) {
            addCriterion("bloodSuger not in", values, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerBetween(String value1, String value2) {
            addCriterion("bloodSuger between", value1, value2, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodsugerNotBetween(String value1, String value2) {
            addCriterion("bloodSuger not between", value1, value2, "bloodsuger");
            return (Criteria) this;
        }

        public Criteria andBloodpressureIsNull() {
            addCriterion("bloodPressure is null");
            return (Criteria) this;
        }

        public Criteria andBloodpressureIsNotNull() {
            addCriterion("bloodPressure is not null");
            return (Criteria) this;
        }

        public Criteria andBloodpressureEqualTo(String value) {
            addCriterion("bloodPressure =", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotEqualTo(String value) {
            addCriterion("bloodPressure <>", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureGreaterThan(String value) {
            addCriterion("bloodPressure >", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureGreaterThanOrEqualTo(String value) {
            addCriterion("bloodPressure >=", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureLessThan(String value) {
            addCriterion("bloodPressure <", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureLessThanOrEqualTo(String value) {
            addCriterion("bloodPressure <=", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureLike(String value) {
            addCriterion("bloodPressure like", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotLike(String value) {
            addCriterion("bloodPressure not like", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureIn(List<String> values) {
            addCriterion("bloodPressure in", values, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotIn(List<String> values) {
            addCriterion("bloodPressure not in", values, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureBetween(String value1, String value2) {
            addCriterion("bloodPressure between", value1, value2, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotBetween(String value1, String value2) {
            addCriterion("bloodPressure not between", value1, value2, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenIsNull() {
            addCriterion("bloodOxygen is null");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenIsNotNull() {
            addCriterion("bloodOxygen is not null");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenEqualTo(String value) {
            addCriterion("bloodOxygen =", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotEqualTo(String value) {
            addCriterion("bloodOxygen <>", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenGreaterThan(String value) {
            addCriterion("bloodOxygen >", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenGreaterThanOrEqualTo(String value) {
            addCriterion("bloodOxygen >=", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenLessThan(String value) {
            addCriterion("bloodOxygen <", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenLessThanOrEqualTo(String value) {
            addCriterion("bloodOxygen <=", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenLike(String value) {
            addCriterion("bloodOxygen like", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotLike(String value) {
            addCriterion("bloodOxygen not like", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenIn(List<String> values) {
            addCriterion("bloodOxygen in", values, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotIn(List<String> values) {
            addCriterion("bloodOxygen not in", values, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenBetween(String value1, String value2) {
            addCriterion("bloodOxygen between", value1, value2, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotBetween(String value1, String value2) {
            addCriterion("bloodOxygen not between", value1, value2, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andHeightweightIsNull() {
            addCriterion("heightWeight is null");
            return (Criteria) this;
        }

        public Criteria andHeightweightIsNotNull() {
            addCriterion("heightWeight is not null");
            return (Criteria) this;
        }

        public Criteria andHeightweightEqualTo(String value) {
            addCriterion("heightWeight =", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightNotEqualTo(String value) {
            addCriterion("heightWeight <>", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightGreaterThan(String value) {
            addCriterion("heightWeight >", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightGreaterThanOrEqualTo(String value) {
            addCriterion("heightWeight >=", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightLessThan(String value) {
            addCriterion("heightWeight <", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightLessThanOrEqualTo(String value) {
            addCriterion("heightWeight <=", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightLike(String value) {
            addCriterion("heightWeight like", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightNotLike(String value) {
            addCriterion("heightWeight not like", value, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightIn(List<String> values) {
            addCriterion("heightWeight in", values, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightNotIn(List<String> values) {
            addCriterion("heightWeight not in", values, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightBetween(String value1, String value2) {
            addCriterion("heightWeight between", value1, value2, "heightweight");
            return (Criteria) this;
        }

        public Criteria andHeightweightNotBetween(String value1, String value2) {
            addCriterion("heightWeight not between", value1, value2, "heightweight");
            return (Criteria) this;
        }

        public Criteria andCholesterolIsNull() {
            addCriterion("cholesterol is null");
            return (Criteria) this;
        }

        public Criteria andCholesterolIsNotNull() {
            addCriterion("cholesterol is not null");
            return (Criteria) this;
        }

        public Criteria andCholesterolEqualTo(String value) {
            addCriterion("cholesterol =", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolNotEqualTo(String value) {
            addCriterion("cholesterol <>", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolGreaterThan(String value) {
            addCriterion("cholesterol >", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolGreaterThanOrEqualTo(String value) {
            addCriterion("cholesterol >=", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolLessThan(String value) {
            addCriterion("cholesterol <", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolLessThanOrEqualTo(String value) {
            addCriterion("cholesterol <=", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolLike(String value) {
            addCriterion("cholesterol like", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolNotLike(String value) {
            addCriterion("cholesterol not like", value, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolIn(List<String> values) {
            addCriterion("cholesterol in", values, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolNotIn(List<String> values) {
            addCriterion("cholesterol not in", values, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolBetween(String value1, String value2) {
            addCriterion("cholesterol between", value1, value2, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andCholesterolNotBetween(String value1, String value2) {
            addCriterion("cholesterol not between", value1, value2, "cholesterol");
            return (Criteria) this;
        }

        public Criteria andUricacidIsNull() {
            addCriterion("uricAcid is null");
            return (Criteria) this;
        }

        public Criteria andUricacidIsNotNull() {
            addCriterion("uricAcid is not null");
            return (Criteria) this;
        }

        public Criteria andUricacidEqualTo(String value) {
            addCriterion("uricAcid =", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidNotEqualTo(String value) {
            addCriterion("uricAcid <>", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidGreaterThan(String value) {
            addCriterion("uricAcid >", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidGreaterThanOrEqualTo(String value) {
            addCriterion("uricAcid >=", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidLessThan(String value) {
            addCriterion("uricAcid <", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidLessThanOrEqualTo(String value) {
            addCriterion("uricAcid <=", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidLike(String value) {
            addCriterion("uricAcid like", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidNotLike(String value) {
            addCriterion("uricAcid not like", value, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidIn(List<String> values) {
            addCriterion("uricAcid in", values, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidNotIn(List<String> values) {
            addCriterion("uricAcid not in", values, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidBetween(String value1, String value2) {
            addCriterion("uricAcid between", value1, value2, "uricacid");
            return (Criteria) this;
        }

        public Criteria andUricacidNotBetween(String value1, String value2) {
            addCriterion("uricAcid not between", value1, value2, "uricacid");
            return (Criteria) this;
        }

        public Criteria andBonedensityIsNull() {
            addCriterion("boneDensity is null");
            return (Criteria) this;
        }

        public Criteria andBonedensityIsNotNull() {
            addCriterion("boneDensity is not null");
            return (Criteria) this;
        }

        public Criteria andBonedensityEqualTo(String value) {
            addCriterion("boneDensity =", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityNotEqualTo(String value) {
            addCriterion("boneDensity <>", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityGreaterThan(String value) {
            addCriterion("boneDensity >", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityGreaterThanOrEqualTo(String value) {
            addCriterion("boneDensity >=", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityLessThan(String value) {
            addCriterion("boneDensity <", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityLessThanOrEqualTo(String value) {
            addCriterion("boneDensity <=", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityLike(String value) {
            addCriterion("boneDensity like", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityNotLike(String value) {
            addCriterion("boneDensity not like", value, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityIn(List<String> values) {
            addCriterion("boneDensity in", values, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityNotIn(List<String> values) {
            addCriterion("boneDensity not in", values, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityBetween(String value1, String value2) {
            addCriterion("boneDensity between", value1, value2, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andBonedensityNotBetween(String value1, String value2) {
            addCriterion("boneDensity not between", value1, value2, "bonedensity");
            return (Criteria) this;
        }

        public Criteria andSleepIsNull() {
            addCriterion("sleep is null");
            return (Criteria) this;
        }

        public Criteria andSleepIsNotNull() {
            addCriterion("sleep is not null");
            return (Criteria) this;
        }

        public Criteria andSleepEqualTo(String value) {
            addCriterion("sleep =", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepNotEqualTo(String value) {
            addCriterion("sleep <>", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepGreaterThan(String value) {
            addCriterion("sleep >", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepGreaterThanOrEqualTo(String value) {
            addCriterion("sleep >=", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepLessThan(String value) {
            addCriterion("sleep <", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepLessThanOrEqualTo(String value) {
            addCriterion("sleep <=", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepLike(String value) {
            addCriterion("sleep like", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepNotLike(String value) {
            addCriterion("sleep not like", value, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepIn(List<String> values) {
            addCriterion("sleep in", values, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepNotIn(List<String> values) {
            addCriterion("sleep not in", values, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepBetween(String value1, String value2) {
            addCriterion("sleep between", value1, value2, "sleep");
            return (Criteria) this;
        }

        public Criteria andSleepNotBetween(String value1, String value2) {
            addCriterion("sleep not between", value1, value2, "sleep");
            return (Criteria) this;
        }

        public Criteria andHeartrateIsNull() {
            addCriterion("heartRate is null");
            return (Criteria) this;
        }

        public Criteria andHeartrateIsNotNull() {
            addCriterion("heartRate is not null");
            return (Criteria) this;
        }

        public Criteria andHeartrateEqualTo(String value) {
            addCriterion("heartRate =", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateNotEqualTo(String value) {
            addCriterion("heartRate <>", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateGreaterThan(String value) {
            addCriterion("heartRate >", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateGreaterThanOrEqualTo(String value) {
            addCriterion("heartRate >=", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateLessThan(String value) {
            addCriterion("heartRate <", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateLessThanOrEqualTo(String value) {
            addCriterion("heartRate <=", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateLike(String value) {
            addCriterion("heartRate like", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateNotLike(String value) {
            addCriterion("heartRate not like", value, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateIn(List<String> values) {
            addCriterion("heartRate in", values, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateNotIn(List<String> values) {
            addCriterion("heartRate not in", values, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateBetween(String value1, String value2) {
            addCriterion("heartRate between", value1, value2, "heartrate");
            return (Criteria) this;
        }

        public Criteria andHeartrateNotBetween(String value1, String value2) {
            addCriterion("heartRate not between", value1, value2, "heartrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table elderhealthinfo
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 14 20:40:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table elderhealthinfo
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}