package com.medicalcare.user.pojo;

import java.util.Date;

public class Elderaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer actionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionType
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String actiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionConsume
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String actionconsume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionStartTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Date actionstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionEndTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Date actionendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionContent
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String actioncontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elderaction.actionDescribe
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String actiondescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionId
     *
     * @return the value of elderaction.actionId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getActionid() {
        return actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionId
     *
     * @param actionid the value for elderaction.actionId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActionid(Integer actionid) {
        this.actionid = actionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionType
     *
     * @return the value of elderaction.actionType
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getActiontype() {
        return actiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionType
     *
     * @param actiontype the value for elderaction.actionType
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActiontype(String actiontype) {
        this.actiontype = actiontype == null ? null : actiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionConsume
     *
     * @return the value of elderaction.actionConsume
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getActionconsume() {
        return actionconsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionConsume
     *
     * @param actionconsume the value for elderaction.actionConsume
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActionconsume(String actionconsume) {
        this.actionconsume = actionconsume == null ? null : actionconsume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionStartTime
     *
     * @return the value of elderaction.actionStartTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Date getActionstarttime() {
        return actionstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionStartTime
     *
     * @param actionstarttime the value for elderaction.actionStartTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActionstarttime(Date actionstarttime) {
        this.actionstarttime = actionstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionEndTime
     *
     * @return the value of elderaction.actionEndTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Date getActionendtime() {
        return actionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionEndTime
     *
     * @param actionendtime the value for elderaction.actionEndTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActionendtime(Date actionendtime) {
        this.actionendtime = actionendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionContent
     *
     * @return the value of elderaction.actionContent
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getActioncontent() {
        return actioncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionContent
     *
     * @param actioncontent the value for elderaction.actionContent
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActioncontent(String actioncontent) {
        this.actioncontent = actioncontent == null ? null : actioncontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elderaction.actionDescribe
     *
     * @return the value of elderaction.actionDescribe
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getActiondescribe() {
        return actiondescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elderaction.actionDescribe
     *
     * @param actiondescribe the value for elderaction.actionDescribe
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setActiondescribe(String actiondescribe) {
        this.actiondescribe = actiondescribe == null ? null : actiondescribe.trim();
    }
}