package com.medicalcare.user.pojo;

import java.util.Date;

public class Hosp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.hospId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer hospid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.hospName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String hospname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.deparementId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer deparementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.sickRoom
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String sickroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.hospNumber
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String hospnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.hospStartTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Date hospstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.hospEndTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Date hospendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.leaveHosp
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Byte leavehosp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp.hospDescribe
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String hospdescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.hospId
     *
     * @return the value of hosp.hospId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getHospid() {
        return hospid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.hospId
     *
     * @param hospid the value for hosp.hospId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHospid(Integer hospid) {
        this.hospid = hospid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.hospName
     *
     * @return the value of hosp.hospName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getHospname() {
        return hospname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.hospName
     *
     * @param hospname the value for hosp.hospName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHospname(String hospname) {
        this.hospname = hospname == null ? null : hospname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.deparementId
     *
     * @return the value of hosp.deparementId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getDeparementid() {
        return deparementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.deparementId
     *
     * @param deparementid the value for hosp.deparementId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setDeparementid(Integer deparementid) {
        this.deparementid = deparementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.sickRoom
     *
     * @return the value of hosp.sickRoom
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getSickroom() {
        return sickroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.sickRoom
     *
     * @param sickroom the value for hosp.sickRoom
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setSickroom(String sickroom) {
        this.sickroom = sickroom == null ? null : sickroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.hospNumber
     *
     * @return the value of hosp.hospNumber
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getHospnumber() {
        return hospnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.hospNumber
     *
     * @param hospnumber the value for hosp.hospNumber
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHospnumber(String hospnumber) {
        this.hospnumber = hospnumber == null ? null : hospnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.hospStartTime
     *
     * @return the value of hosp.hospStartTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Date getHospstarttime() {
        return hospstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.hospStartTime
     *
     * @param hospstarttime the value for hosp.hospStartTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHospstarttime(Date hospstarttime) {
        this.hospstarttime = hospstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.hospEndTime
     *
     * @return the value of hosp.hospEndTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Date getHospendtime() {
        return hospendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.hospEndTime
     *
     * @param hospendtime the value for hosp.hospEndTime
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHospendtime(Date hospendtime) {
        this.hospendtime = hospendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.leaveHosp
     *
     * @return the value of hosp.leaveHosp
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Byte getLeavehosp() {
        return leavehosp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.leaveHosp
     *
     * @param leavehosp the value for hosp.leaveHosp
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setLeavehosp(Byte leavehosp) {
        this.leavehosp = leavehosp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp.hospDescribe
     *
     * @return the value of hosp.hospDescribe
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getHospdescribe() {
        return hospdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp.hospDescribe
     *
     * @param hospdescribe the value for hosp.hospDescribe
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setHospdescribe(String hospdescribe) {
        this.hospdescribe = hospdescribe == null ? null : hospdescribe.trim();
    }
}