package com.medicalcare.user.pojo;

import java.util.Date;

public class Userbasicinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasicinfo.userId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasicinfo.userName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasicinfo.userPassword
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasicinfo.userPhone
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasicinfo.userType
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbasicinfo.RegisterDate
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    private Date registerdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasicinfo.userId
     *
     * @return the value of userbasicinfo.userId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasicinfo.userId
     *
     * @param userid the value for userbasicinfo.userId
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasicinfo.userName
     *
     * @return the value of userbasicinfo.userName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasicinfo.userName
     *
     * @param username the value for userbasicinfo.userName
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasicinfo.userPassword
     *
     * @return the value of userbasicinfo.userPassword
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasicinfo.userPassword
     *
     * @param userpassword the value for userbasicinfo.userPassword
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasicinfo.userPhone
     *
     * @return the value of userbasicinfo.userPhone
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasicinfo.userPhone
     *
     * @param userphone the value for userbasicinfo.userPhone
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasicinfo.userType
     *
     * @return the value of userbasicinfo.userType
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasicinfo.userType
     *
     * @param usertype the value for userbasicinfo.userType
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbasicinfo.RegisterDate
     *
     * @return the value of userbasicinfo.RegisterDate
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbasicinfo.RegisterDate
     *
     * @param registerdate the value for userbasicinfo.RegisterDate
     *
     * @mbggenerated Fri Sep 14 20:40:09 CST 2018
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }
}